-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgoUef/MLhUP25f+Kf+BkWnrjPqsNtMachUxlSFcEZprOgCgYIKoZIzj0DAQehRANCAATyP/71vTcAdemp0YqC3m1CzzbWAMtd81gFVPYpPMyw8sosvwHGLB2qfoDv+bkQTY7LAWPH+VBuXCp0NRmKX8qR
-----END PRIVATE KEY-----